import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeMenuProvider  } from './(HomePage)/Navbar/Theme/ThemeMenuProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <title>Yie Portfolio</title>
        <ThemeMenuProvider >
          {children}
        </ThemeMenuProvider >
        </body>
    </html>
  )
}
